= Documento de Requisitos
:page-layout: base
:numbered:
:toc:
:toc-title: {page-title}
:toc-placement!:
include::links.adoc[]

toc::[]

== Introdução

=== Propósito
Este documento tem por objetivo descrever e especificar os requisitos que devem ser atendidos pelo Sistema Oncoped Web, de forma a satisfazer as necessidades do serviço de quimioterapia do Hospital Peter Pan, servindo, ainda, de principal documento de referência para futuras implementações.

=== Público Alvo
Este documento se destina-se aos desenvolvedores e implementadores participantes do projeto.

=== Dados Gerais
* Nome do Projeto: Sistema para Gerenciamento de Serviço de Quimioterapia Pediátrica
* Sigla do Projeto: ONCOPED WEB

=== Envolvidos no Projeto

|===
| Nome | E-mail | Papel

| Francisco J Nogueira
| fjosenogueira@gmail.com
| Desenvolvedor/Analista

| Antônio Gomes
| xxxxx
| xxxxx


|===

=== Justificativa do Projeto


=== Objetivos do Projeto
Análise, desenvolvimento, implantação, disponibilização de um sistema web acessado via internet que permita cadastrar, acompanhar, organizar e gerir os processos de um serviço de quimioterapia pediátrica.

=== Escopo
O sistema a ser desenvolvido tem por objetivo principal gerenciar as fases do tratamento oncohematológico pediátrico no serviço de quimioterapia do Centro Pediátrico do Câncer (Hospital Peter Pan), gerando informações para tomada de decisão, viabilizando um melhor direcionamento durante o tratamento.

Ele deverá facilitar a gestão das atividades diárias de um serviço de quimioterapia como, por exemplo, a realização do agendamento do paciente, acompanhamento do protocolo de tratamento, visualização da escala de serviço dos profissionais oncologistas, prescrição de quimioterápicos etc. 

=== Premissas
Todo o desenvolvimento será realizado fazendo uso de boas práticas e padrões de projeto em um ambiente .Net.


== Visão Geral do Produto

Ele deverá facilitar a gestão das atividades diárias de um serviço de quimioterapia como, por exemplo, a realização do agendamento do paciente, acompanhamento do protocolo de tratamento, visualização da escala de serviço dos profissionais oncologistas, prescrição de quimioterápicos etc. 

=== Cenário Atual
O Serviço de OncoHematologia do Centro Pediátrico do Câncer (CPC) atende, em média, cerca de 80 pacientes/dia. São consultas prévias necessárias para avaliação clínica e prescrição de quimioterápicos. Seu público é formado por crianças e jovens portadores de câncer, oriundos das mais diversas regiões do Ceará, bem como de outros Estados.
O CPC conta há 15 anos com um sistema chamado ONCOPED, desenvolvido em Delphi 4 e tendo como base de dados tabelas paradox. O mesmo possui, dentre outras funcionalidades, a possibilidade de gerar prescrições de medicamentos baseadas no protocolo de tratamento em uso pelo paciente, bem como tornar possível a previsão do próximo dia de tratamento/consulta, e que droga será utilizada. Na época representou um notável avanço, pois tais características do sistema possibilitava ao oncologista dispor de um tempo maior para conversar com o paciente e seu acompanhante, melhorando o relacionamento médico-paciente, promovendo um atendimento mais humanizado uma vez que atividades rotineiras e repetitivas ficavam a cargo do sistema.
Atualmente o referido sistema encontra-se em desuso pois, além de seus bugs constantes e sua manutenção complexa, é necessário um conhecimento profundo do funcionamento do sistema para a inclusão de novos protocolos. Isso fez com que apenas a funcionalidade de agendamento seja utilizada do sistema. 
Principais motivos para o desuso:
•	Bugs constantes relacionados em parte pela limitação física do tamanho de tabelas paradox, ocasionando corrompimento dos arquivos de índices e dados (quem lembra de DBF?);
•	A inclusão de novos protocolos de tratamento é muito complexa, dependendo de um profissional que conheça o funcionamento interno do sistema. Resultou no retorno a prescrição “na mão” reduzindo o tempo de contato médico-paciente e lentidão no atendimento;
•	Apesar de possuir  o código fonte do aplicativo sua manutenção é inviável, pois não há qualquer documentação e seu código foi escrito de forma muito obscura, sem qualquer técnica que possibilitasse um entendimento posterior (nível Magaiver);
•	O sistema roda apenas em uma máquina.


=== Atores
|===
| Nome | Definição

| Médico
| Médico oncologista responsável por realizar a consulta, diagnósticar e escolher o protocolo de tratamento a ser utilizado;

| Médico
| Médico oncologista responsável por realizar a consulta, diagnósticar e escolher o protocolo de tratamento a ser utilizado;



|===
* Médico Oncologista;
* Secretária;
* Paciente;
* Coordenadores;
* Assessores;
* Equipe de apoio dos coordenadores.


== Requisitos Funcionais
=== Manter Usuário
* Anexar currículos da equipe;
* Gerenciar perfil usuário;
* Integração via LDAP.

=== Manter Tipos de Proposição

=== Manter Tratamentos de Proposição

=== Manter Proposição
* Incluir número do protocolo MJDOC e contemplar SEI;
* Consumir dados das duas casas legislativas;
* Acessar trâmites das proposições nas duas casas legislativas e posicionamentos dos ministérios;
* Atrelar registro de manifestações, comentários e documentos administrativos relacionados;
* Priorização das Proposições para reunião de Pauta;
* Anexar arquivo;

=== Manter Exposições de Motivos
* *Internas (de autoria do MJ)*:
** Anexar notas elaboradas;
** Associar EMI’s arquivadas sobre o mesmo tema;
** Relacionar a EMI com o PL e norma originada.
* *Externo (de autoria de outros órgãos em coautoria com o MJ)*:
** Anexar texto das EMI's recebidas via SIDOF;
** Juntar notas elaboradas;
** Anexar documentos administrativos relacionados;
** Classificar EMI’s.

=== Manter Manifestação
* Notas;
* Notas técnicas;
* Pareceres de Sanção;
* Manter demandas dos Parlamentares;
* Posicionamentos preliminares;
* Anexar textos das manifestações;
* Vincular documento de Manifestação.

=== Manter Contatos da Secretária
* Agendar compromissos.
* Possibilitar a associação e unificação de contatos em duplicidade.
* Permitir fácil usabilidade e interface amigável focada na secretária.
* Realizar controle de distribuição de demandas e prazos para resposta
** Anexar arquivos e notificações no módulo de tarefas;
** Filtro de destinatários;
** Notificação via e-mail;
** Priorização de tarefas;
** Possibilitar o usuário verificar suas tarefas;
** Viabilizar a geração em mais de um formato de arquivo;
** Gerar relatórios referentes à distribuição das demandas, responsáveis e prazos;
** Manter demanda de parlamentares;
** Requerimento Informativo;
** Criar alerta quando o prazo de Requerimento estiver próximo.

=== Consultar Documentos - SEI
* Ofícios;
* Memorandos;
* Despachos.

=== Montar Pauta Semanal
* Consultar proposições da Câmara dos Deputados e Senado Federal;
* Vincular as tramitações das Casas;
* Agenda Legislativa: Relatório Semanal de todas as proposições, editável;
* Evidenciar os posicionamentos ministeriais e os acontecidos oriundos da SAL.

=== Categorizar (tags) conteúdo
* Proposições;
* Manifestações;
* Exposição de Motivos (EM).
* Pesquisas por:
** Forma livre, pesquisando todo conteúdo do portal;
** Conteúdo dentro dos Documentos;
** Indexar temas por termos autorizados;
** Categorias.

=== Incluir dados do processo - SEI

=== Consulta e verificação dos dados existentes no Banco de Dados do EDENS que serão salvos no novo sistema SISLEGIS

=== Notificações de alterações de texto ou tramitações nos Projetos de Lei

=== Manter Portarias - Referência
* Pesquisa de Portarias para o público externo
* Migração de dados de Portarias do sistema atual para o sistema a ser desenvolvido.

Mecanismo de notificação automática na medida em que mudanças nas proposições prioritárias ou já inclusas no sistema apareçam nas pautas da Câmara dos Deputados, Senado Federal e Congresso Nacional. 


== Requisitos Não Funcionais
* *Segurança*: O Sistema terá um procedimento de autorização de usuários, nos quais terão que se identificar usando um (login) e uma senha. Somente usuários autorizados terão acesso aos dados.
* *Desempenho*: Os requisitos de performance deverão ser explicitados em documento de arquitetura.
* *Usabilidade*: Deverão ser utilizados novos padrões de usabilidade e interface amigáveis.
* *Confiabilidade*: O Sistema deverá ficar disponível 24 (Vinte e Quatro) horas por dia durante 07 (Sete) dias da semana, durante todo o ano. As paradas para manutenção de qualquer espécie neste período deverão ser negociadas com a SAL e quando necessárias devem acontecer fora do horário comercial.
* *Padrões Aplicáveis*: O Sistema será desenvolvido na Plataforma Java. Maiores detalhes sobre a codificação do sistema estarão contemplados no documento de arquitetura.
* *Hardware*: Desktop e Notebook. Tablet e Mobile será feito estudo de viabilidade.
* *Documentação*: Os artefatos produzidos estarão em conformidade com as melhores práticas. As adaptações poderão ser realizadas nos modelos da documentação, caso necessárias.
* *Browsers suportados*: o Sistema será homologado para os browsers Mozilla Firefox e Google Chrome.


== Glossário

[glossary]
EMI:: - Exposição de Motivos Interministerial

PL:: - Projeto de Lei

SAL:: - Secretária de Assunto Legislativo

SIDOF:: - Sistema de Geração e Tramitação de Documentos

ASPAR:: - Assessoria Parlamentar

Requerimento:: - Proposição de alguma providência

Proposição:: - Toda matéria sujeita à aprovação do Plenário da Assembleia

Manifestação:: - Resposta à uma proposição ou requerimento 

// vim: set syntax=asciidoc:
