= Documento de Requisitos
:page-layout: base
:numbered:
:toc:
:toc-title: {page-title}
:toc-placement!:
include::links.adoc[]

toc::[]

== Introdução

=== Propósito
Este documento tem por objetivo descrever e especificar os requisitos que devem ser atendidos pelo Sistema Oncoped Web, de forma a satisfazer as necessidades do serviço de quimioterapia do Hospital Peter Pan, servindo, ainda, de principal documento de referência para futuras implementações.

=== Público Alvo
Este documento se destina-se aos desenvolvedores e implementadores participantes do projeto.

=== Dados Gerais
* Nome do Projeto: Sistema para Gerenciamento de Serviço de Quimioterapia Pediátrica
* Sigla do Projeto: ONCOPED WEB

=== Envolvidos no Projeto

|===
| Nome | E-mail | Papel

| Francisco J Nogueira
| fjosenogueira@gmail.com
| Desenvolvedor/Analista

| Antônio Gomes
| xxxxx
| xxxxx


|===

=== Justificativa do Projeto


=== Objetivos do Projeto
Análise, desenvolvimento, implantação, disponibilização de um sistema web acessado via internet que permita cadastrar, acompanhar, organizar e gerir os processos de um serviço de quimioterapia pediátrica.

=== Escopo
O sistema a ser desenvolvido tem por objetivo principal gerenciar as fases do tratamento oncohematológico pediátrico no serviço de quimioterapia do Centro Pediátrico do Câncer (Hospital Peter Pan), gerando informações para tomada de decisão, viabilizando um melhor direcionamento durante o tratamento.

Ele deverá facilitar a gestão das atividades diárias de um serviço de quimioterapia como, por exemplo, a realização do agendamento do paciente, acompanhamento do protocolo de tratamento, visualização da escala de serviço dos profissionais oncologistas, prescrição de quimioterápicos etc. 

=== Premissas
Todo o desenvolvimento será realizado fazendo uso de boas práticas e padrões de projeto em um ambiente .Net.


== Visão Geral do Produto

Ele deverá facilitar a gestão das atividades diárias de um serviço de quimioterapia como, por exemplo, a realização do agendamento do paciente, acompanhamento do protocolo de tratamento, visualização da escala de serviço dos profissionais oncologistas, prescrição de quimioterápicos etc. 

=== Cenário Atual
O Serviço de OncoHematologia do Centro Pediátrico do Câncer (CPC) atende, em média, cerca de 80 pacientes/dia. São consultas prévias necessárias para avaliação clínica e prescrição de quimioterápicos. Seu público é formado por crianças e jovens portadores de câncer, oriundos das mais diversas regiões do Ceará, bem como de outros Estados.
O CPC conta há 15 anos com um sistema chamado ONCOPED, desenvolvido em Delphi 4 e tendo como base de dados tabelas paradox. O mesmo possui, dentre outras funcionalidades, a possibilidade de gerar prescrições de medicamentos baseadas no protocolo de tratamento em uso pelo paciente, bem como tornar possível a previsão do próximo dia de tratamento/consulta, e que droga será utilizada. Na época representou um notável avanço, pois tais características do sistema possibilitava ao oncologista dispor de um tempo maior para conversar com o paciente e seu acompanhante, melhorando o relacionamento médico-paciente, promovendo um atendimento mais humanizado uma vez que atividades rotineiras e repetitivas ficavam a cargo do sistema.
Atualmente o referido sistema encontra-se em desuso pois, além de seus bugs constantes e sua manutenção complexa, é necessário um conhecimento profundo do funcionamento do sistema para a inclusão de novos protocolos. Isso fez com que apenas a funcionalidade de agendamento seja utilizada do sistema. 
Principais motivos para o desuso: 

* Bugs constantes relacionados em parte pela limitação física do tamanho de tabelas paradox, ocasionando corrompimento dos arquivos de índices e dados (quem lembra de DBF?);

*	A inclusão de novos protocolos de tratamento é muito complexa, dependendo de um profissional que conheça o funcionamento interno do sistema. Resultou no retorno a prescrição “na mão” reduzindo o tempo de contato médico-paciente e lentidão no atendimento;
* Apesar de possuir  o código fonte do aplicativo sua manutenção é inviável, pois não há qualquer documentação e seu código foi escrito de forma muito obscura, sem qualquer técnica que possibilitasse um entendimento posterior (nível Magaiver);
* O sistema roda apenas em uma máquina.


=== Atores
|===
| Nome | Definição

| Médico
| Médico oncologista responsável por realizar a consulta, diagnósticar e escolher o protocolo de tratamento a ser utilizado;

| Médico
| Médico oncologista responsável por realizar a consulta, diagnósticar e escolher o protocolo de tratamento a ser utilizado;



|===

== Requisitos Funcionais

=== Manter Usuário
* Gerenciar perfil usuário;
* Autenticar no Active Directory (Samba4) em uso na rede do HIAS

=== Buscar Paciente no HOSPUB
* Possibilitar a consulta do paciente na base de dados do HIAS através de chamadas ao webservice existe, permitindo atualizar os dados;
* Usará como parâmetro de busca o número do prontuário, código obrigatório e único dentro da unidade hospitalar;

=== Manter Paciente
* Possibilidade de adicionar/atualizar dados  com base nas informações contidas no HOSPUB;
* Armazenar dados pessoais do paciente, bem como do responsável;
* Diagnóstico recebido e protocolo a ser utilizado;
* Peso e Estatura atual do paciente (calculo da superfície corpórea);

=== Atualizar Peso e Estatura
* Registrar peso, estatura e data da aferição;
* Manter histórico de registros anteriores para futura avaliação.

=== Manter Médico
* Dados pessoais do médico;
* Especialidade / Formação;

=== Manter Escala
* Montar escala de trabalho mensal dos médicos;
* Inserir feriados;


=== Manter Protocolo

=== Manter Droga

=== Manter Diagnóstico

=== Manter Agenda

== Requisitos Não Funcionais
* *Segurança*: O Sistema terá um procedimento de autorização de usuários, nos quais terão que se identificar usando um (login) e uma senha. Somente usuários autorizados terão acesso aos dados.
* *Desempenho*: Os requisitos de performance deverão ser explicitados em documento de arquitetura.
* *Usabilidade*: Deverão ser utilizados padrões de usabilidade e interface amigáveis.
* *Confiabilidade*: O Sistema deverá ficar disponível 24 (Vinte e Quatro) horas por dia durante 07 (Sete) dias da semana, durante todo o ano. As paradas para manutenção de qualquer espécie neste período deverão ser negociadas com a coordenação do serviço.
* *Padrões Aplicáveis*: O Sistema será desenvolvido na Plataforma .Net.
* *Hardware*: Desktop e Notebook. Tablet e Mobile será feito estudo de viabilidade posteriormente.
* *Documentação*: Os artefatos produzidos estarão em conformidade com as melhores práticas. As adaptações poderão ser realizadas nos modelos da documentação, caso necessárias.
* *Browsers suportados*: o Sistema será homologado para os browsers Mozilla Firefox e Google Chrome.


== Glossário

[glossary]
APP:: - Associação Peter Pan

CPC:: - Centro Pediátrico do Câncer

HIAS:: - Hospital Infantil Albert Sabin

HOSPUB:: - Sistema de Gestão Hospitalar utilizado pelo HIAS que mantem todos os pacientes atendidos na unidade.

SISAPP:: - Sistema atualmente em desenvolvimento para gerenciar atividades da APP. Fará uso de informações do ONCOPED.

Quimiterapia Sequencial:: - Medicação contra o câncer administrada em dias seguidos, sendo necessária a internação.

Quimiterapia Dia:: - Medicação contra o câncer administrada no dia da consulta, possibilitando o retorno do paciente a sua residência.

Oncologista:: - Médico especialista no tratamento do câncer.



// vim: set syntax=asciidoc:
